baseURL = "/"
languageCode = "en-us"


[params]
footerContent= "Copyright Twenty Twenty One | International Justice Mission Philippines"
menuButtonText= "Learn More"
SiteLogo = "/IJM_Logo_Horizontal_White_ForWeb.png"


[[menu.main]]
Name = "About"
url = "/about"


